### ISSUE TITLE
Env file is failing to import onnx

### ISSUE THREAD

**Issue by jeremycheminf** [chembl/chembl_multitask_model#3]
Hello
The file environment.yml is fialing to run via conda env because onnx 12.0.0 is not found.
Is it onnx 1.12.0?
Trying with fresh install without the env fail to load models , onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from chembl_31_multitask.onnx failed:Protobuf parsing failed. , when running ort_session = onnxruntime.InferenceSession("chembl_31_multitask.onnx") and I'm trying to reproduce the env and see if it works there.
Do you know which version of onnxruntime is needed? It's not in env file but required to run the prediction script.
Thank you

**Comment by rajarshi** [comment]
Hi, I'm facing the same issue. Conda shows a 12.0.0 (https://anaconda.org/conda-forge/onnx) but it doesn't install

Instead it install 1.14. With that version, it also needs `onnxruntime`, but with those packages the published code doesn't seem to work. I had to modify line 26 to 

```
ort_session = onnxruntime.InferenceSession("trained_models/chembl_33_model/chembl_33_multitask.onnx", providers=['CPUExecutionProvider'])
```
but after that I'm seeing the following error

```
2023-09-20 14:44:32.979444239 [E:onnxruntime:Default, env.cc:251 ThreadMain] pthread_setaffinity_np failed for thread: 81323, index: 19, mask: {1, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2023-09-20 14:44:33.024431388 [E:onnxruntime:Default, env.cc:251 ThreadMain] pthread_setaffinity_np failed for thread: 81304, index: 0, mask: {2, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
```

Any ideas what the issue might be?

**Comment by jeremycheminf** [comment]
Still error
`
ort_session = onnxruntime.InferenceSession("chembl_33_multitask.onnx", providers=['CPUExecutionProvider'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeremy/mambaforge/envs/model_test/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jeremy/mambaforge/envs/model_test/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from chembl_33_multitask.onnx failed:Protobuf parsing failed.
`
I'll check with new env

**Comment by eloyfelix** [comment]
Hi, it seems I messed the conda env file when updating the chembl 33 model + the javascript and C++ examples.
I've also recently abandoned conda so I'll replace the conda env file by the requirements.txt file I'm using now and probably add a github action/dockerfile so this doesn't happen again.

Thanks @rajarshi for finding the fix.

[requirements.txt](https://github.com/chembl/chembl_multitask_model/files/12676978/requirements.txt)

**Comment by jeremycheminf** [comment]
Right, I had another look, and it was my fault on file downloaded!
Need to be
wget -O chembl_33_multitask.onnx https://github.com/chembl/chembl_multitask_model/blob/main/trained_models/chembl_33_model/chembl_33_multitask.onnx\?raw=true

with ?raw=true so the file I got before was not correct.

Once installed with onnx and runtime it worked.
Thank you!
